### ISSUE TITLE
Performance vs MetaOcaml?

### ISSUE THREAD

**Issue by bluddy** [stedolan/ppx_stage#8]
Sorry for using this as a communication channel. I wish github had something better built-in.

How does performance compare to MetaOcaml? Specifically for the Stream Fusion library?

**Comment by stedolan** [comment]
Do you mean performance of the generated code, how long it takes to generate the code, or how long it takes the generator to compile?

Performance of the generated code is identical, since it's generating the same code (well, `ppx_stage` picks different variable names, but that's about it). I haven't benchmarked how long it takes to generate code. I imagine MetaOCaml compiles faster, because it doesn't have to expand and then marshal parse trees, but I haven't benchmarked that either.
